[module]
[module.hugoVersion]
extended = true
min = "0.141.0"
max = "0.148.2"
# In config/_default/config.toml
baseURL = "https://anotheruzername.github.io/"
title = "My New Site" # You can change this too